### ISSUE TITLE
ImportError: No module named core.config

### ISSUE THREAD

**Issue by nemonameless** [facebookresearch/video-long-term-feature-banks#10]
I run the install steps successfully ,but when try to training, I run 'source activate video-lfb' first and meet this problem. 

I also see this problem in https://github.com/facebookresearch/video-nonlocal-net/issues/9 and  https://github.com/facebookresearch/Detectron/issues/475, but have no idea solving this .

**Comment by guancheng817** [comment]
Hello, I met same question, Have you solved it? Thanks .

**Comment by chaoyuaw** [comment]
Hi, Have you tried to run the following command?
export PYTHONPATH=/path/to/video-long-term-feature-banks/lib:$PYTHONPATH

(please replace "/path/to/video-long-term-feature-banks" by the actual full path of your cloned video-long-term-feature-banks folder)
