### ISSUE TITLE
Error in making TensorMathPairwise

### ISSUE THREAD

**Issue by xinyuwang1126** [facebookresearch/video-long-term-feature-banks#12]
Hi,

I have followed the instruction of installation but encountered the following error:

cc: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-5/README.Bugs> for instructions.
CMake Error at torch_generated_THCTensorMathPairwise.cu.o.Release.cmake:279 (message):
  Error generating file
  /home/ubuntu/pytorch/build/caffe2/CMakeFiles/torch.dir/__/aten/src/THC/./torch_generated_THCTensorMathPairwise.cu.o

caffe2/CMakeFiles/torch.dir/build.make:6810: recipe for target 'caffe2/CMakeFiles/torch.dir/__/aten/src/THC/torch_generated_THCTensorMathPairwise.cu.o' failed
make[2]: *** [caffe2/CMakeFiles/torch.dir/__/aten/src/THC/torch_generated_THCTensorMathPairwise.cu.o] Error 1
CMakeFiles/Makefile2:6049: recipe for target 'caffe2/CMakeFiles/torch.dir/all' failed
make[1]: *** [caffe2/CMakeFiles/torch.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2
Traceback (most recent call last):
  File "setup.py", line 753, in <module>
    build_deps()
  File "setup.py", line 327, in build_deps
    cmake=cmake)
  File "/home/ubuntu/pytorch/tools/build_pytorch_libs.py", line 64, in build_caffe2
    cmake.build(my_env)
  File "/home/ubuntu/pytorch/tools/setup_helpers/cmake.py", line 350, in build
    self.run(build_args, my_env)
  File "/home/ubuntu/pytorch/tools/setup_helpers/cmake.py", line 108, in run
    check_call(command, cwd=self.build_dir, env=env)
  File "/home/ubuntu/anaconda3/envs/DIVA/lib/python2.7/subprocess.py", line 190, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--target', 'install', '--config', 'Release', '--', '-j', '1']' returned non-zero exit status 2

I am using CUDA9.0 and CUDNN7.6 on a 16.04 Ubuntu machine.
Do you have an idea of what is going on?

Also, I noticed that in the instruction it said you need to add a customized operator affine_nd_op, but the command actually will delete the whole video folder in caffe2, will it cause any other problems?
Thanks in advance!

**Comment by chaoyuaw** [comment]
Hi @xinyuwang1126 , thanks for your question. Unfortunately, I don't know what caused this error. Just curious, were you able to successfully build caffe2 (official caffe2 only; without LFB repository)?

Regarding your second question, yes, for all experiments we do here, we don't need anything that's in the video folder. So for simplicity I just replaced it. If your project requires using anything from it, please feel free to add them back.

**Comment by chaoyuaw** [comment]
Hi @xinyuwang1126 , were you able to solve the issue?

**Comment by xinyuwang1126** [comment]
Hi @chaoyuaw ,
Thanks for following up! I have changed to a machine with the exact same environment and built it successfully.
