### ISSUE TITLE
[Query] Approximate training time

### ISSUE THREAD

**Issue by TheShadow29** [facebookresearch/video-long-term-feature-banks#13]
Could you share some estimate of the training time of the model(s) and the gpu resources used?

**Comment by chaoyuaw** [comment]
Hi @TheShadow29, Thanks for the question. 

For detailed training time of each experiment, you can read from the log files provided in https://github.com/facebookresearch/video-long-term-feature-banks#results

Roughly speaking, for Charades, it finishes in 7 hours including all evaluations we do along training. For AVA, it takes close to 2 days. For EPIC-Kitchens, it takes 20/12 hours for verbs/nouns respectively. 

All experiments use a machine with 8 P100 GPUs.

**Comment by TheShadow29** [comment]
@chaoyuaw thanks for the prompt and detailed answer. From your experience do the observations on charades transfer to ava as well?

**Comment by chaoyuaw** [comment]
Not necessarily. I think Charades and AVA are different in many ways.
