### ISSUE TITLE
About ava load boxes and label

### ISSUE THREAD

**Issue by wjchaoGit** [facebookresearch/video-long-term-feature-banks#16]
Thanks for your code!

I notice that in the code:
https://github.com/facebookresearch/video-long-term-feature-banks/blob/623972f5c2ab85fb37496a62b5888466895c6559/lib/datasets/ava.py#L77
For the GT annotation file(ava_train_v2.1.csv), the row[7] is the person_id. However, it is used as score in the code.

Is this a mistake?

**Comment by chaoyuaw** [comment]
Thanks for your question! The original csv files do not have the person_id field; It was added later on (https://groups.google.com/forum/#!topic/ava-dataset-users/XiVrZxbs4Rw). So I think if you use the new version, please modify accordingly. Sorry for the confusion!
