### ISSUE TITLE
About the model pretrained on visual genome.

### ISSUE THREAD

**Issue by yelantf** [facebookresearch/video-long-term-feature-banks#17]
Thanks for sharing your codes!
I was trying to use the Visual Genome pre-trained model for object detection on some other image datasets, but then I found that there were no final layers (`cls_score` and `bbox_pred`) in it. I guess that the provided model is modified for finetuning. Could you please provide an unmodified version? Thank you very much!

**Comment by chaoyuaw** [comment]
Sure, please find the full model at
https://github.com/facebookresearch/video-long-term-feature-banks/issues/14
Thanks!

**Comment by yelantf** [comment]
Sorry to bother you again. One more question, what is `class_embedding` and where does it come from? Thanks again for your generous help and quick reply.

**Comment by chaoyuaw** [comment]
Hi @yelantingfeng, in this project I only used this pre-trained model for fine-tuning, and I don't know much more beyond this, so unfortunately I'm not able to share more on this weight file.
