### ISSUE TITLE
Could you share your ffmpeg settings?

### ISSUE THREAD

**Issue by chenz97** [facebookresearch/video-long-term-feature-banks#18]
Thanks for your code!

When cutting videos for the AVA dataset using cut_videos.sh you provided, I found that using a different ffmpeg version or just using the same ffmpeg version but in different machines may lead to different output sizes, where a notable difference lies in data rates. The script used is exactly the same. Could you please share your ffmpeg settings (platform, version etc.)? Thank you very much!

**Comment by chaoyuaw** [comment]
Hi @chenz97, Thanks for letting us know the issue. The following is the version I used. Please let me know if you need any further information. I used a CentOS Linux machine. 




                build: ffmpeg-git-20180625-64bit-static.tar.xz
              version: gd25c94524

                  gcc: 6.3.0
                 yasm: 1.3.0.36.ge2569
                 nasm: 2.13.03

               libaom: 0.1.0-9275-g727ffdb61
               libass: 0.14.0
               libvpx: 1.7.0-532-gbd6b274dc
              libvmaf: 0.6.2
              libx264: 0.155.2901 7d0ff22
              libx265: 2.8+23-656b5b442f0b
              libxvid: 1.3.4-1+b2
              libwebp: 0.5.2
              libzimg: 2.7.4
            libgnutls: 3.5.18
            libtheora: 1.2.0alpha1+git
            libfrei0r: 1.5.0-1
           libvidstab: 1.10
          libfreetype: 2.6.3-3.2
          libopenjpeg: 2.3.0

              libalsa: 1.1.6
              libsoxr: 0.1.3
              libopus: 1.3-beta
             libspeex: 1.2
            libvorbis: 1.3.6
           libmp3lame: 3.100
        librubberband: 1.8.1
       libvo-amrwbenc: 0.1.3-1
    libopencore-amrnb: 0.1.3-2.1+b2
    libopencore-amrwb: 0.1.3-2.1+b2

      For HEVC/H.265 encoding:  ffmpeg -h encoder=libx265
                                http://x265.readthedocs.org/en/default/cli.html#standalone-executable-options

      For AVC/H.264 encoding:   ffmpeg -h encoder=libx264
                                http://mewiki.project357.com/wiki/X264_Settings

                 FFmpeg Wiki:   https://trac.ffmpeg.org/wiki

**Comment by chenz97** [comment]
@chaoyuaw Thank you! It seems that the specific ffmpeg version you used is hard to find now. I will try using the ffmpeg on my machine and see if I can reproduce your results first.

**Comment by luckcodingdog** [comment]
Hi, @chenz97.
i had a question which your version of ffmpeg and your configuration. I test with 
ava_r101_baseline | R101-I3D-NL | 3D CNN | 23.2, just got map 21.7, i thought different ffmpeg
version and configuration may have different result, my ffmpeg version is 2.8.15 and configuration
list below:
ffmpeg version 2.8.15 Copyright (c) 2000-2018 the FFmpeg developers
  built with gcc 4.8.5 (GCC) 20150623 (Red Hat 4.8.5-36)
  configuration: 
  libavutil      54. 31.100 / 54. 31.100
  libavcodec     56. 60.100 / 56. 60.100
  libavformat    56. 40.101 / 56. 40.101
  libavdevice    56.  4.100 / 56.  4.100
  libavfilter     5. 40.101 /  5. 40.101
  libswscale      3.  1.101 /  3.  1.101
  libswresample   1.  2.101 /  1.  2.101
Hyper fast Audio and Video encoder

Thanks a lot !

**Comment by chenz97** [comment]
Hi @luckcodingdog ,
I'm now using ffmpeg 2.8.15 with configuration listed below:
ffmpeg version 2.8.15-0ubuntu0.16.04.1 Copyright (c) 2000-2018 the FFmpeg developers
  built with gcc 5.4.0 (Ubuntu 5.4.0-6ubuntu1~16.04.10) 20160609

  libavutil      54. 31.100 / 54. 31.100
  libavcodec     56. 60.100 / 56. 60.100
  libavformat    56. 40.101 / 56. 40.101
  libavdevice    56.  4.100 / 56.  4.100
  libavfilter     5. 40.101 /  5. 40.101
  libavresample   2.  1.  0 /  2.  1.  0
  libswscale      3.  1.101 /  3.  1.101
  libswresample   1.  2.101 /  1.  2.101
  libpostproc    53.  3.100 / 53.  3.100

BTW, I can get mAP 23.2 using ava_r101_baseline | R101-I3D-NL | 3D CNN.

**Comment by luckcodingdog** [comment]
Hi, @chenz97, i am sorry to bother you again.
If you encounter a question, use 'cut-ava_videos'script with '.mp4' videos like below:
ffmpeg -ss 900 -t 901 -i 0f39OWEqJ24.mp4 0f39OWEqJ24_15min.mp4
the program arise error:
[aac @ 0x1793660] The encoder 'aac' is experimental but experimental codecs are not enabled, add '-strict -2' if you want to use it.
Besides, extract with '.webm', it encounter the error of "Encoder (codec vp8) not found for output stream #0:0".
i wonder if these errors make my result is less than the authors'.
Thanks a lot in advance !
