### ISSUE TITLE
backbone model (without non-local blocks) pretrained on kinetics-400

### ISSUE THREAD

**Issue by ZilinGao** [facebookresearch/video-long-term-feature-banks#21]
Thanks for your nice code!

In this work, the baseline model employed is non-local network, pretrained on kinetics-400. I want to conduct some experiments on the backbone model without non-local on Charades dataset. So, I need a backbone model pretrained on kinetics-400. Have you ever trained it? If it is posible, would you please release it?

Thanks!

**Comment by chaoyuaw** [comment]
Hi @ZilinGao, yes, you could find those models in https://github.com/facebookresearch/video-nonlocal-net
I believe they should be compatible with this code base.

**Comment by ZilinGao** [comment]
Thanks for your response!

I compare pretrained models in two paper on kinetics. It seems that they are slightly different. Simply speaking, the output size of residual stage 5 in non-local paper is 7x7x4, and in long-term paper, it looks like 14x14x4. 

And I notice that the non-local performance reported in long-term is absolutely identical with the one in non-local paper: top-1 acc 74.9, top-5 acc 91.6.

So, are the two pretrained models  slightly different as above mentioned? If they are different, the non-local performance reported in long-term paper refers to which one?

Thanks a lot!

**Comment by chaoyuaw** [comment]
While we use the output=(14x14) model for AVA, it's pretrained on Kinetics following the Kinetics default (output=(7x7)). That is why the pretrained model in the LFB paper and the model in non-local paper have the same Kinetics performance (because the are the same model).

**Comment by ZilinGao** [comment]
OK. It is very clear now. Many thanks!
