### ISSUE TITLE
About the number of key frames used

### ISSUE THREAD

**Issue by chenz97** [facebookresearch/video-long-term-feature-banks#23]
Hi! Thank you for your code and sorry to bother again.

I checked your log and found that in AVA logs, the key frames used are:
```
[INFO: ava.py:  101]: Number of unique boxes: 666191
[INFO: ava.py:  102]: Number of annotations: 1607900
[INFO: ava.py:  123]: 193301 keyframes used.
```

However, when I ran your code (`ava_train_v2.1.csv` and `ava_train_predicted_boxes.csv` are downloaded accroding to your instructions), my output log looks like:

```
[INFO: ava.py:  101]: Number of unique boxes: 664550
[INFO: ava.py:  102]: Number of annotations: 1603805
[INFO: ava.py:  123]: 193296 keyframes used.
```

I also took out the code snippet of `load_boxes_and_labels()` in `ava.py` and ran it, getting the same results. 

I'm wondering where the difference comes from. Thanks a lot!

**Comment by chaoyuaw** [comment]
Hi @chenz97, of course! I'm happy to help.

Were you able to run all steps in https://github.com/facebookresearch/video-long-term-feature-banks/blob/master/DATASET.md#ava successfully? Also, did you download and use the "frame lists" we provided? Also, could you check if the frames in downloaded "frame lists" match the jpg frames you have?

**Comment by chenz97** [comment]
Hi @chaoyuaw , I have run all the steps in DASASET.md. `_7oWZq_s_Sk.mkv` cannot be successfully converted to 15 min video, so I downloaded it manually using youtube-dl and run the following steps. I have used your "frame lists" and checked that all the frames specified in "frame lists" exist. In fact, some of the folders have one or two more frames than specified in "frame lists" (but my output numbers are smaller than yours).

The `Number of unique boxes:` and `Number of annotations:` output above seem to come from `load_boxes_and_labels()` in `ava.py`. I checked the code and found that for training the output only depends on `filenames` which should be `ava_train_v2.1.csv` and `ava_train_predicted_boxes.csv` according to `config.py`, and `detect_thresh` which should be 0.9. I also took out the code snippet and ran it, getting the same results. I'm suspecting a different `ava_train_predicted_boxes.csv`.

Do you have any idea then? Thank you!

**Comment by chaoyuaw** [comment]
Hi @chenz97, 

Thanks for your detailed information. 

Can you try downloading ava_train_v2.1.csv from
https://research.google.com/ava/download/ava_v2.1.zip ?
It seems
https://research.google.com/ava/download/ava_train_v1.0.csv
provides a different file from what I used.  (ava_train_v2.1.csv in ava_v2.1.zip looks the same as what I used though.)

**Comment by chenz97** [comment]
Hi @chaoyuaw ,

Thank you for your prompt reply.

I have tried downloading ava_train_v2.1.csv as instructed above, but the results remain the same. Actually, in download_annotations.sh the v2.1 file is already used: 
`wget https://research.google.com/ava/download/ava_train_v2.1.csv -P ${DATA_DIR}`

**Comment by chaoyuaw** [comment]
Hi @chenz97, That's really strange...
Just to double check, my ava_train_predicted_boxes.csv has 1033086 lines, and my ava_train_v2.1.csv has 837318 lines. Do you have the same?

**Comment by chenz97** [comment]
Hi @chaoyuaw , thanks for your info.
I have checked the files and the two numbers are exactly the same with yours.

Just to make sure, when training the baseline model, the parameters of [load_boxes_and_labels](https://github.com/facebookresearch/video-long-term-feature-banks/blob/master/lib/datasets/ava.py#L54) should be `filenames=['ava_train_v2.1.csv', 'ava_train_predicted_boxes.csv'], is_train=True, detect_thresh=0.9, full_eval=False`, right? 

If so, could you please run the code snippet manually (with `AVA_VALID_FRAMES = range(902, 1799)`) and see if the  `Number of unique boxes:` and `Number of annotations:` match the log you provided?

Thank you very much!

**Comment by chaoyuaw** [comment]
Hi @chenz97, sorry for the delayed reply and thanks for confirming. I'll investigate and get back to you soon.

**Comment by chaoyuaw** [comment]
Hi @chenz97, unfortunately I still couldn't reproduce the issue you see. The `Number of unique boxes` and `Number of annotations` I see match the logs we provided.

Just a few thoughts on how to debug it:
1. Can you share with me your full stdout and stderr logs? 
2. Is the repository you use a clean git cloned-repository? Maybe it worths doing a diff to the original code base, just to confirm? 
3. Can you try running testing only to see if you can get expected #frames, etc. and expected mAP? (This will also tell us whether the issue is caused by ava_train_predicted_boxes.csv ). 

Thanks!

**Comment by wjchaoGit** [comment]
Hi, @chenz97 @chaoyuaw 
Issue #16  may lead to this problem.

When I ran the original code with the new version csv file, the number of key frames used is `193296`.
After modifying the code, the number of key frames used is `193301`.

**Comment by chaoyuaw** [comment]
Oh, thanks a lot @wjchaoGit!! This might be it!

@chenz97, please let me know if it fixes the issue. Thank you!

**Comment by chenz97** [comment]
Hi @wjchaoGit , thank you very much!! That's it!

Hi @chaoyuaw , yes, the issue gets fixed! Thank you for your help with great patience!!
