### ISSUE TITLE
GPU memory issue

### ISSUE THREAD

**Issue by Scofieldtangsiwei** [facebookresearch/video-long-term-feature-banks#24]
Hi! Thank you for your code!  

I tried to run the code on my GTX 1080Ti 12GB. But it ran out of memory. I changed the batch size from 16 to 8, and it happened again. I wonder if it is normal? And what GPU did you use for training?

Thank you so much!

**Comment by chaoyuaw** [comment]
Hi @Scofieldtangsiwei, thanks for your questions! I don't think it's expected. For memory usage and GPU information, I recommend taking a look at the "log files" available at https://github.com/facebookresearch/video-long-term-feature-banks#results

I'm wondering how many GPUs you are using. We used 8, so batch size 16 means 2 clips per GPU. If you use <8 GPUs, you might want to decrease the batch size accordingly.

**Comment by Scofieldtangsiwei** [comment]
Hi @chaoyuaw, thank you so much for your reply! I am using 8 V100 16GB GPUs for training. I checked your log file, and found out the bug in my training configuration. I used multiprocess for each GPU which caused the out-of-memory issue. I changed the setting back to single process later and finally solved the problem. Thank you so much!

**Comment by Yingying6** [comment]
> Hi @chaoyuaw, thank you so much for your reply! I am using 8 V100 16GB GPUs for training. I checked your log file, and found out the bug in my training configuration. I used multiprocess for each GPU which caused the out-of-memory issue. I changed the setting back to single process later and finally solved the problem. Thank you so much!

Hi Scofield, where did you find the multiprocess threads number? Many thanks.

**Comment by Yingying6** [comment]
Hi @chaoyuaw Firstly thank you for such a robust project! For the GPU memory issue. 
Though i have reduced the batch size to 4 (four 1080 Ti GPUs in total hence 1 for each card) and also changed the number of processes in Dataloader (I assume this is what @Scofieldtangsiwei mentioned in this post), i still got 'out of memory' error.

**Comment by Yingying6** [comment]
> Hi @chaoyuaw Firstly thank you for such a robust project! For the GPU memory issue.
> Though i have reduced the batch size to 4 (four 1080 Ti GPUs in total hence 1 for each card) and also changed the number of processes in Dataloader (I assume this is what @Scofieldtangsiwei mentioned in this post), i still got 'out of memory' error.

Btw, training the baseline with the same setting has no problem at all while training the **lfb** has the out of memory issue. - I carefully checked the charades_r101_lfb_nl.yaml to ensure the same bathsize settings as in charades_r101_baseline.yaml. 
Any other factors that will cause the out-of-memory issue when specifically training with LFB? Many thanks.

**Comment by chaoyuaw** [comment]
Hi @Yingying6 , are you able to share the output log files (including both stderr and stdout) with me? I can take a look to see if I can identify anything.

**Comment by Yingying6** [comment]
> Hi @Yingying6 , are you able to share the output log files (including both stderr and stdout) with me? I can take a look to see if I can identify anything.

Thank you Chaoyuan. My problem - there were some zombie processes - now everything is all right. Again thanks for the paper and the thorough experiments.
