### ISSUE TITLE
error while installing caffe2 from pytorch source code

### ISSUE THREAD

**Issue by banshee1** [facebookresearch/video-long-term-feature-banks#28]
I am trying to install pytroch from source code and I met an error while compiling:
[ 86%] Building CXX object caffe2/CMakeFiles/torch.dir/__/torch/csrc/autograd/profiler_cuda.cpp.o [ 86%] Building CXX object caffe2/CMakeFiles/torch.dir/__/torch/csrc/autograd/functions/comm.cpp.o [ 86%] Building CXX object caffe2/CMakeFiles/torch.dir/__/torch/csrc/cuda/comm.cpp.o [ 86%] Linking CXX shared library ../lib/libtorch.so /usr/bin/ld: /home/wjfan/anaconda3/envs/video-lfb/lib/libmagma.a(error.cpp.o): unrecognized relocation (0x2a) in section .text'
/usr/bin/ld: final link failed: Bad value
collect2: error: ld returned 1 exit status
make[2]: *** [lib/libtorch.so] Error 1
make[1]: *** [caffe2/CMakeFiles/torch.dir/all] Error 2
make: *** [all] Error 2
Traceback (most recent call last):
File "setup.py", line 759, in 
build_deps()
File "setup.py", line 321, in build_deps
cmake=cmake)
File "/media/sdf/wjfan/Pytorch/pytorch/tools/build_pytorch_libs.py", line 63, in build_caffe2
cmake.build(my_env)
File "/media/sdf/wjfan/Pytorch/pytorch/tools/setup_helpers/cmake.py", line 329, in build
self.run(build_args, my_env)
File "/media/sdf/wjfan/Pytorch/pytorch/tools/setup_helpers/cmake.py", line 142, in run
check_call(command, cwd=self.build_dir, env=env)
File "/home/wjfan/anaconda3/envs/video-lfb/lib/python2.7/subprocess.py", line 190, in check_call
raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--target', 'install', '--config', 'Release', '--', '-j', '56']' returned non-zero exit status 2 `

I have no idea how this error happen and how to fix it.
my cuda version is 10.0, cudnn version is 7.30
please help me!

**Comment by chaoyuaw** [comment]
Hi @banshee1, Sorry for the late reply. 

Reading the conversations in https://github.com/pytorch/pytorch/issues/26100, are you saying that if you don't replace the "pytorch/caffe2/video" folder, you are able to install successfully? 

If that's the case, could you please try adding the contents in "caffe2_customized_ops/video/" into "pytorch/caffe2/video/",  without removing and replacing it? 

Thanks!

**Comment by banshee1** [comment]
> Hi @banshee1, Sorry for the late reply.
> 
> Reading the conversations in [pytorch/pytorch#26100](https://github.com/pytorch/pytorch/issues/26100), are you saying that if you don't replace the "pytorch/caffe2/video" folder, you are able to install successfully?
> 
> If that's the case, could you please try adding the contents in "caffe2_customized_ops/video/" into "pytorch/caffe2/video/", without removing and replacing it?
> 
> Thanks!

Thanks for your apply. I find that this error is not raised by adding '/caffe2_customized_ops/video' into 'pytorch/caffe2/video', it happens only if I install "magma-cuda100'' by running 'conda install -c pytorch magma-cuda100'. If I compile pytorch without installing it, I can install successfully. So what does 'magma' used for?  Actually I can run the code by installing pytorch&caffe2 without magma, but it run really really slowly. Does magma is used for computation acceleration?

**Comment by banshee1** [comment]
> Hi @banshee1, Sorry for the late reply.
> 
> Reading the conversations in [pytorch/pytorch#26100](https://github.com/pytorch/pytorch/issues/26100), are you saying that if you don't replace the "pytorch/caffe2/video" folder, you are able to install successfully?
> 
> If that's the case, could you please try adding the contents in "caffe2_customized_ops/video/" into "pytorch/caffe2/video/", without removing and replacing it?
> 
> Thanks!

The error might be raised because it failed to link libmagma.a, I guess.

**Comment by banshee1** [comment]
> Hi @banshee1, Sorry for the late reply.
> 
> Reading the conversations in [pytorch/pytorch#26100](https://github.com/pytorch/pytorch/issues/26100), are you saying that if you don't replace the "pytorch/caffe2/video" folder, you are able to install successfully?
> 
> If that's the case, could you please try adding the contents in "caffe2_customized_ops/video/" into "pytorch/caffe2/video/", without removing and replacing it?
> 
> Thanks!

I have solved this problem by degrading 'magma-cuda' version. But now I get a new one, the code run really slow, I takes about 'time: 2-3.5' per 10 iters with 8 TITANX. I run this code on another machine with 4 2080Ti but get a much faster speed around 'time:0.8' per 10 iters. And the GPU-Utils in 'nvidia-smi' just flashes from 0 to a number like 90-99 all the time. What might cause this probem? Could you please help me figure it out?

**Comment by chaoyuaw** [comment]
Hi @banshee1, Glad that you solved the issue!

Do the two machines have the same disk and the same number of CPUs? I'd guess that it might be IO issues (one machine has a faster IO speed than the other). I guess you can try using only 4 GPUs on the 8-GPU machine and make sure that you run exactly the same thing on the two machines and compare the results to help debugging.

**Comment by banshee1** [comment]
> Hi @banshee1, Glad that you solved the issue!
> 
> Do the two machines have the same disk and the same number of CPUs? I'd guess that it might be IO issues (one machine has a faster IO speed than the other). I guess you can try using only 4 GPUs on the 8-GPU machine and make sure that you run exactly the same thing on the two machines and compare the results to help debugging.

I don't really understand how this happened. I googled for it and others said that it's caused by the 'avx' module. So I recompiled pytorch with adding a avx cmake option, the warnings of 'avx is not compiled with caffe2' is still raised but the ETA reduce from 6 days to 3 days. It seems reasonable to me now, thanks for your reply!
