### ISSUE TITLE
About person detection and cmake: undefined reference to `pthread_create'

### ISSUE THREAD

**Issue by DirtyHarryLYL** [facebookresearch/video-long-term-feature-banks#3]
Thanks for your sharing and great work. I have some questions about the detections and cmake.
1. I noticed that the person detector is finetuned on the ava dataset. Is it 
finetuned on the gt boxes of ava train set?
2. Sorry for the question about cmake. I met a weird problem during compling, cmake output an error :
"CMakeFiles/cmTC_72608.dir/CheckSymbolExists.c.o: In function `main':
CheckSymbolExists.c:(.text+0x1b): undefined reference to `pthread_create'
collect2: error: ld returned 1 exit status"
In the repo of pytorch I have found some answers but not work for me. Have you ever met this?
I have tried different cmake versions from 3.5-3.12. 
[CMakeError.log](https://github.com/facebookresearch/video-long-term-feature-banks/files/3124199/CMakeError.log)

**Comment by chaoyuaw** [comment]
1. Yes, it's fine-tuned on the GT boxes of the AVA training set.

2. Did you install all dependencies (https://github.com/pytorch/pytorch#from-source)? This seems related to https://github.com/facebookresearch/video-nonlocal-net/issues/2

**Comment by DirtyHarryLYL** [comment]
Thanks, Chao-Yuan. 
It was my conda prefix path problem. Now everything goes smoothly.
