### ISSUE TITLE
How long will it take to train ava dataset v2 ,rtx2080ti ?

### ISSUE THREAD

**Issue by hushunda** [facebookresearch/video-long-term-feature-banks#32]
How long will it take to train ava dataset v2 ,rtx2080ti ?

**Comment by chaoyuaw** [comment]
Hi @hushunda , 

For AVA, it takes close to 2 days with 8 P100 GPUs. I'm not sure about rtx2080ti. 

For detailed training time of each experiment, you can read from the log files provided in https://github.com/facebookresearch/video-long-term-feature-banks#results
