### ISSUE TITLE
about ava_eval_helper.py

### ISSUE THREAD

**Issue by hushunda** [facebookresearch/video-long-term-feature-banks#33]
the code in lib/utils/avaeval_helper.py 

`from utils.ava_evaluation import object_detection_evaluation .  

from utils.ava_evaluation import standard_fields`

but I cannot find the 'utils.ava_evaluation' file,can you give me some help?

**Comment by haooooooqi** [comment]
Please follow the instruction in [dataset_tools/ava/download_annotations.sh](https://github.com/facebookresearch/video-long-term-feature-banks/blob/8953fe040ce142c4480840af535d2f497d7c1b1f/dataset_tools/ava/download_annotations.sh)

**Comment by hushunda** [comment]
Thank you for your prompt reply
