### ISSUE TITLE
some confusion about STO experiment

### ISSUE THREAD

**Issue by ZilinGao** [facebookresearch/video-long-term-feature-banks#34]
Hi, I have some confusion about the experiment on STO. Hope to get your reply.

My confusion is about the STO result in Tab.4. Under backbone R-50-I3D-NL, STO gets mAP of 39.6. Following is my comprehension about this experiment setting.

1. STO employs proposal (same to LFB).
2. The number of STO module is two (same to LFB).
3. STO module is the modified non-local module in Fig.4 (same to LFB).

Whether my comprehension is correct? Hope for your response. Thanks a lot~

**Comment by chaoyuaw** [comment]
Hi @ZilinGao , 

In Table 4 (Charades), 
1. For Charades, STO doesn't use proposals. It follows EPIC verbs setting: see "Adaptation to Segment-Level Tasks." in Section 5.1.
2. Yes, 2 layers of NL blocks for STO.
3. We tried both and post-activation version worked better. Please see details in Table 7 in Appendix I of https://arxiv.org/pdf/1812.05038.pdf

Please feel free to let me know if you have further questions :)

**Comment by ZilinGao** [comment]
@chaoyuaw  Thanks for your reply~ I have no more question~
