### ISSUE TITLE
How to make sure ROI of long-term feature?

### ISSUE THREAD

**Issue by luckcodingdog** [facebookresearch/video-long-term-feature-banks#37]
Hi, i have a question, how to match your short-term  person  feature with long-term feature bank? for example, i have bounding box of one person at 1000 second,  we extract short-term c3d feature at 999s-1000s,  long-term feature is extract c3d feature from 971 to 1030 (60s), how to make sure ROi of each second? 
thanks a lot in advance!

**Comment by chaoyuaw** [comment]
Hi @luckcodingdog , I'm not sure if I understand your question correctly. The short-term feature and the long-term features are connected through FBO (implemented in  https://github.com/facebookresearch/video-long-term-feature-banks/blob/master/lib/models/lfb_helper.py). Could you please explain what you want to make sure again?
