### ISSUE TITLE
About model structure

### ISSUE THREAD

**Issue by WinstonDeng** [facebookresearch/video-long-term-feature-banks#40]
Sorry to bother you.
I dont understand how the output of FBO together with short-term features are entered into classifier on fig3(b) in your paper. Are these two terms sum first or inputed into the classifier respectively?

**Comment by chaoyuaw** [comment]
Hi, those two are concatenated before being fed into a linear classifier. You could find the details in

https://github.com/facebookresearch/video-long-term-feature-banks/blob/master/lib/models/resnet_video.py#L314
and
https://github.com/facebookresearch/video-long-term-feature-banks/blob/master/lib/models/head_helper.py#L82

Thanks!
