### ISSUE TITLE
Fine-tuning

### ISSUE THREAD

**Issue by srinivasn1** [facebookresearch/video-long-term-feature-banks#50]
Is there support for fine-tuning the models? How would you achieve it.

Thanks

**Comment by chaoyuaw** [comment]
Yes, fine-tuning is supported. In fact, all models from this repo are fine-tuned from a Kinetics-400 pretrained model. If you want to fine tune from a different model (e.g., a model already trained on AVA/Charades/EPIC-Kitchens), you can simply set TRAIN.PARAMS_FILE to the model file you want to fine-tune from, and train the model as usual. 

Please feel free to let me know if you have further questions! :)

**Comment by srinivasn1** [comment]
Sorry, I wasn't clear about the question. I meant to ask about how to freeze the intermediate layers and train only the last few layers.

Thanks for the quick response. I appreciate it.

**Comment by chaoyuaw** [comment]
There's a StopGradient operator to achieve this. For example, we can add something like
https://github.com/facebookresearch/Detectron/blob/8170b25b425967f8f1c7d715bea3c5b8d9536cd8/detectron/modeling/ResNet.py#L105

**Comment by srinivasn1** [comment]
Thank you.
