### ISSUE TITLE
Charades Dataset - Extracting video clips during training

### ISSUE THREAD

**Issue by srinivasn1** [facebookresearch/video-long-term-feature-banks#51]
In the paper, for the charades dataset you have stated that "We use the RGB frames at 24 FPS provided by the dataset authors. We sample training and testing clips (32 frames) with a temporal stride of 4 following STRG [52], resulting in input clips spanning 125 frames (∼5.2 seconds)."

 From my  understanding, if there are N number of frames in a video, training clips of size 32 frames are extracted from the N frames with a temporal stride of 4 secs i.e. the first training clip has frames 0-31, second training clip has framed 4-36 so on.
How does "resulting in input clips spanning 125 frames (∼5.2 seconds)" formed? Is each input clip only 125 frames?

Could you elaborate more on the process used to extract the input clips for training? This will help understand how to prepare a new action dataset for training.

Thanks.

**Comment by chaoyuaw** [comment]
Thanks for the questions. The temporal stride is "4 frames" instead of "4 seconds". Thus 32 frames with stride 4 cover (1 + 31 * 4) == 125 frames == 125 / 24 ~ 5.2 seconds.

**Comment by srinivasn1** [comment]
Thank you!

**Comment by YunhaoDu** [comment]
@srinivasn1 Hi, It seems like you have successfully install and use the LFB. I'm facing some problems when I install Pytorch from source. Could you tell me your version of pytorch and gcc ?
