### ISSUE TITLE
about pytorch and gcc version

### ISSUE THREAD

**Issue by YunhaoDu** [facebookresearch/video-long-term-feature-banks#54]
I'm facing some problems when installing PyTorch from source (python2 setup.py install). Cound anyone who has installed successfully tell me which version of PyTorch and gcc you used? thank you!

**Comment by chaoyuaw** [comment]
Hi @dyh-bupt , Will you be able to share the error messages you see? I'll see if I can recognize anything.

**Comment by chaoyuaw** [comment]
Also, I recommend searching in https://github.com/pytorch/pytorch/issues if it's a PyTorch installation issue instead of an LFB-specific issue.

**Comment by YunhaoDu** [comment]
@chaoyuaw Thanks for your reply, my error messages are shown in issue #55 , i.e.
when I use command "python2 setup.py install", the error is 
`Building wheel torch-1.4.0a0+72e1771
-- Building version 1.4.0a0+72e1771
cmake --build . --target install --config Release -- -j 12
[1/2050] Building CXX object c10/CMakeFiles/c10.dir/core/DefaultDtype.cpp.o
FAILED: c10/CMakeFiles/c10.dir/core/DefaultDtype.cpp.o 
/usr/bin/c++ -DHAVE_MALLOC_USABLE_SIZE=1 -DHAVE_MMAP=1 -DHAVE_SHM_OPEN=1 -DHAVE_SHM_UNLINK=1 -DIDEEP_USE_MKL -DMAGMA_V2 -DONNX_ML=1 -DONNX_NAMESPACE=onnx_torch -DTH_BLAS_MKL -D_FILE_OFFSET_BITS=64 -Dc10_EXPORTS -Iaten/src -I../aten/src -I. -I../ -I../cmake/../third_party/benchmark/include -Icaffe2/contrib/aten -I../third_party/onnx -Ithird_party/onnx -I../third_party/foxi -Ithird_party/foxi -I../c10/.. -isystem third_party/gloo -isystem ../cmake/../third_party/gloo -isystem ../cmake/../third_party/googletest/googlemock/include -isystem ../cmake/../third_party/googletest/googletest/include -isystem ../third_party/protobuf/src -isystem /home/dyh/anaconda3/envs/video-lfb/include -isystem ../third_party/gemmlowp -isystem ../third_party/neon2sse -isystem ../third_party -isystem ../cmake/../third_party/eigen -isystem /home/dyh/anaconda3/envs/video-lfb/include/python2.7 -isystem /home/dyh/anaconda3/envs/video-lfb/lib/python2.7/site-packages/numpy/core/include -isystem ../cmake/../third_party/pybind11/include -isystem /usr/lib/x86_64-linux-gnu/openmpi/include/openmpi -isystem /usr/lib/x86_64-linux-gnu/openmpi/include/openmpi/opal/mca/event/libevent2022/libevent -isystem /usr/lib/x86_64-linux-gnu/openmpi/include/openmpi/opal/mca/event/libevent2022/libevent/include -isystem /usr/lib/x86_64-linux-gnu/openmpi/include -isystem ../cmake/../third_party/cub -isystem ../third_party/ideep/mkl-dnn/include -isystem ../third_party/ideep/include -fvisibility-inlines-hidden -fopenmp -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -O2 -fPIC -Wno-narrowing -Wall -Wextra -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Wno-stringop-overflow -O3  -fPIC -DCAFFE2_USE_GLOO -DCUDA_HAS_FP16=1 -DHAVE_GCC_GET_CPUID -DUSE_AVX -DUSE_AVX2 -DTH_HAVE_THREAD -DC10_BUILD_MAIN_LIB -fvisibility=hidden -std=gnu++11 -MD -MT c10/CMakeFiles/c10.dir/core/DefaultDtype.cpp.o -MF c10/CMakeFiles/c10.dir/core/DefaultDtype.cpp.o.d -o c10/CMakeFiles/c10.dir/core/DefaultDtype.cpp.o -c ../c10/core/DefaultDtype.cpp
c++: error: unrecognized command line option ‘-fdiagnostics-color=always’
c++: error: unrecognized command line option ‘-faligned-new’
`

Note that I'm using gcc/g++-v4.8 and cuda 9.0

**Comment by YunhaoDu** [comment]
@chaoyuaw oh, I've solved this error, but the viersion gcc-4.8 is too old:
![image](https://user-images.githubusercontent.com/50792949/90086664-86158900-dd4d-11ea-9298-6a974d943539.png)
when I use gcc-5.5, another error occurs, like https://github.com/pytorch/pytorch/issues/11183.
So I want to konw which version should I use?

**Comment by YunhaoDu** [comment]
Now I've solved the problem, with gcc5.5, CUDA10.0 and PyTorch1.4.
I'll close this issue.
