### ISSUE TITLE
Python 2 has reached end-of-life and is no longer supported by Pytorch

### ISSUE THREAD

**Issue by Jo-won** [facebookresearch/video-long-term-feature-banks#57]
When installing using the ```python2 setup.py install``` command as in INSTALL.md, i met this error.

![image](https://user-images.githubusercontent.com/46413594/94826255-14e77d80-0442-11eb-822a-bc01fd940989.png)

I had never corrected the ```setup.py``` before, but I annotated it to avoid errors and passed it over, and as the code was executed, this message was left.

```Python 2 has reached end-of-life and is no longer supported by Pytorch```

So I don't think I can turn the code here right now, is there any other way?

**Comment by KevinGrantLee** [comment]
So from PyTorch >= 1.5 (I believe), they dropped python2 support. So what you have to do is to clone an older version of PyTorch. I successfully installed with PyTorch 1.4 (commit 7f73f1d), CUDA 10.0, and CUDNN 7.

```
git clone --recursive https://github.com/pytorch/pytorch
git checkout 7f73f1d
git submodule sync
git submodule update --init --recursive
# ...
```

Don't forget the 2 git submodule lines! When I didn't include them, I got errors.

**Comment by Jo-won** [comment]
@KevinGrantLee Thank you! The code works well if i do as you say.

**Comment by jun0wanan** [comment]
> @KevinGrantLee Thank you! The code works well if i do as you say.

 from caffe2.proto import caffe2_pb2, metanet_pb2, torch_pb2
ImportError: cannot import name caffe2_pb2

hi ，I also find the error ...
can you help me?
