### ISSUE TITLE
Which kind of GPU do you use?

### ISSUE THREAD

**Issue by zhujiagang** [facebookresearch/video-long-term-feature-banks#6]
Sorry to bother you again.

I use the default config file `ava_r101_lfb_nl_3l.yaml`, where the number of GPUs is 8 and batchsize is 16. But I find it will cause out of memory on TiTAN V (12G). So I have to reduce the batchsize to 8, and the current memory is about 8G. I am wondering which kind of GPU you use for experiment and the memory usage. Or I may do something wrong in compiling caffe2, etc

**Comment by chaoyuaw** [comment]
Hi, thanks for your question!

We used P100 GPUs that have 16G memory. The memory usage of our experiments could be found in the output log files (, which are available at https://github.com/facebookresearch/video-long-term-feature-banks#results). Let me know if you need help finding them.

**Comment by zhujiagang** [comment]
Thank you. I don't have P100 GPUs, so I have to reduce the batchsize to 8 and adjust the learning rate schedule.
