### ISSUE TITLE
image size for person detection

### ISSUE THREAD

**Issue by ShoufaChen** [facebookresearch/video-long-term-feature-banks#61]
Hi, @chaoyuaw

May I ask what is the image size for person detection in the eval stage?

Thanks.

**Comment by chaoyuaw** [comment]
Hi @ShoufaChen , 

Thanks for the question! The details of our person detector is available at 
https://github.com/facebookresearch/video-long-term-feature-banks/blob/master/GETTING_STARTED.md#ava-person-detector
In particular, we use 
![Screen Shot 2021-03-05 at 10 08 12 AM](https://user-images.githubusercontent.com/1841547/110141443-c6486180-7d9a-11eb-9c4f-632008af832c.png)

**Comment by ShoufaChen** [comment]
Thanks very much for your reply.
