### ISSUE TITLE
The window size of casual mode

### ISSUE THREAD

**Issue by zhujiagang** [facebookresearch/video-long-term-feature-banks#9]
Sorry to bother you again. I am not sure the window size of casual mode in Table 1 (a). Take the last column (sec. 60) for example, is the length of time window 30 in casual mode, while 60 for batch mode?

**Comment by chaoyuaw** [comment]
Thanks for your question! In the last column, in the causal mode it's from -60 to 0 while in the batch mode it's from -30 to 30.

**Comment by zhujiagang** [comment]
Thanks for your reply.
